base_inference_config: configs/inference/robotwin_fsdp.yaml

port: 29546
save_root: experiments/turn_switch_grpo_check_fsdp
guidance_scale: 1
action_guidance_scale: 1
enable_offload: true
vae_offload: true
text_encoder_cpu_offload: false
prompt_max_sequence_length: 226

fsdp:
  load_transformer_on_cpu: true
  rank0_aux_only: true
  block_only: true
  reshard_after_forward: true
  reduce_dtype: float32
  ac_granularity: all

rl:
  reward:
    type: sparse_success

  use_fsdp: true
  group_size: 2
  rollout_groups_per_update: 1
  update_epochs: 1
  batch_size: 2

  action_noise_std: 0.05
  clip_range: 0.2
  target_kl: null
  entropy_coef: 0.0
  bc_coef: 0.0
  checkpoint_interval: 1
  export_inference_checkpoint: false
  max_grad_norm: 1.0

  validate_logprob_consistency: true
  logprob_consistency_atol: 5.0e-3

  optimizer:
    lr: 1.0e-6
    weight_decay: 0.0
    betas: [0.9, 0.95]

  logprob:
    normalize_denoising_horizon: true
    normalize_action_dim: true

  disable_updates: true
